"""Lexical data: month names, companies, technology terms, abbreviations, units, symbols, currencies.

Keeping this data in one place lets the normalizers build their regexes from it
and makes extending the library (adding a new abbreviation, etc.) a one-line change.

The values are intentionally Turkish — they are the spoken/written forms the
library emits.
"""

# 1..12 -> month name
MONTHS = {
    1: "Ocak", 2: "Şubat", 3: "Mart", 4: "Nisan",
    5: "Mayıs", 6: "Haziran", 7: "Temmuz", 8: "Ağustos",
    9: "Eylül", 10: "Ekim", 11: "Kasım", 12: "Aralık",
}

# Company and brand names -> Turkish TTS spoken form.
# Keys are matched case-insensitively.
COMPANIES = {
    "adobe": "adobi",
    "airbnb": "eyr bi en bi",
    "amazon": "emezın",
    "apple": "epıl",
    "asus": "asus",
    "binance": "baynens",
    "booking": "buking",
    "bosch": "boş",
    "burger king": "börgır king",
    "coca cola": "koka kola",
    "dell": "del",
    "discord": "diskord",
    "dropbox": "dropboks",
    "ebay": "i bey",
    "facebook": "feysbuk",
    "fedex": "fedeks",
    "garanti bbva": "Garanti bebevea",
    "github": "git hab",
    "gmail": "ci meyl",
    "google": "gugıl",
    "hepsiburada": "hepsiburada",
    "hp": "eyç pi",
    "huawei": "huavey",
    "ibm": "ay bi em",
    "ikea": "ikea",
    "instagram": "instagram",
    "intel": "intel",
    "linkedin": "linkdin",
    "logitech": "lojitek",
    "mastercard": "masterkart",
    "mcdonalds": "mekdonalds",
    "media markt": "medya markt",
    "meta": "meta",
    "microsoft": "maykrosoft",
    "netflix": "netfliks",
    "nike": "nayk",
    "nintendo": "nintendo",
    "nvidia": "envidya",
    "openai": "opın ey ay",
    "oracle": "orakıl",
    "paypal": "pey pal",
    "pepsi": "pepsi",
    "philips": "filips",
    "playstation": "pleysteyşın",
    "reddit": "redit",
    "samsung": "samsung",
    "shopify": "şopifay",
    "siemens": "simens",
    "skype": "skayp",
    "slack": "slek",
    "snapchat": "snepçet",
    "sony": "soni",
    "spotify": "spotifay",
    "starbucks": "starbaks",
    "steam": "stim",
    "tesla": "tesla",
    "tiktok": "tik tok",
    "trendyol": "trendyol",
    "turkcell": "türksel",
    "twitch": "tviç",
    "twitter": "tivitır",
    "uber": "ubır",
    "visa": "viza",
    "vodafone": "vodafon",
    "whatsapp": "vatsap",
    "xbox": "eks boks",
    "xiaomi": "şaomi",
    "yahoo": "yahu",
    "yandex": "yandeks",
    "youtube": "yu tub",
    "zoom": "zum",
}

AI_MODEL_TERMS = {
    "GPT": "ci pi ti",
    "LLM": "el el em",
    "RAG": "rag",
    "LoRA": "lo ra",
    "QLoRA": "kyu lo ra",
    "MoE": "mo i",
    "BERT": "bört",
    "RoBERTa": "ro berta",
    "T5": "ti fayv",
    "CLIP": "klip",
    "ViT": "vi ay ti",
    "SAM": "sam",
    "YOLO": "yo lo",
    "DETR": "det er",
    "Whisper": "vispır",
    "WaveNet": "vev net",
    "Tacotron": "takotron",
    "BPE": "bi pi i",
    "SFT": "es ef ti",
    "DPO": "di pi o",
    "PPO": "pi pi o",
    "GRPO": "ci ar pi o",
    "RLHF": "ar el eyç ef",
    "PEFT": "peft",
    "FSDP": "ef es di pi",
    "DDP": "di di pi",
    "ZeRO": "ziro",
    "CUDA": "ku da",
    "ONNX": "oniks",
    "GGUF": "ci ci yu ef",
    "FP32": "ef pi otuz iki",
    "FP16": "ef pi on altı",
    "BF16": "bi ef on altı",
    "INT8": "int sekiz",
    "INT4": "int dört",
    "TPU": "ti pi yu",
    "GPU": "ci pi yu",
    "NPU": "en pi yu",
    "AI": "ey ay",
    "ML": "em el",
    "DL": "di el",
    "MLP": "em el pi",
    "CNN": "si en en",
    "RNN": "ar en en",
    "DNN": "di en en",
    "ANN": "ey en en",
    "GNN": "ci en en",
    "GCN": "ci si en",
    "GAT": "ci ey ti",
    "LSTM": "el es ti em",
    "GRU": "ci ar yu",
    "GAN": "gan",
    "VAE": "vi ey i",
    "AE": "ey i",
    "RL": "ar el",
    "DRL": "di ar el",
    "IRL": "ay ar el",
    "NLP": "en el pi",
    "NLU": "en el yu",
    "NLG": "en el ci",
    "TTS": "ti ti es",
    "ASR": "ey es ar",
    "STT": "es ti ti",
    "OCR": "o si ar",
    "CV": "si vi",
    "XAI": "eks ey ay",
    "AGI": "ey ci ay",
    "ANI": "ey en ay",
    "ASI": "ey es ay",
    "MLOps": "em el ops",
    "LLMOps": "el el em ops",
    "AIOps": "ey ay ops",
    "LangChain": "leng çeyn",
    "MCP": "em si pi",
    "ReLU": "re lu",
    "GELU": "ce lu",
    "SiLU": "si lu",
    "AdamW": "edım dabıl yu",
    "SGD": "es ci di",
    "KL": "key el",
    "KD": "key di",
    "PCA": "pi si ey",
    "tSNE": "ti es en i",
    "UMAP": "yu map",
    "KNN": "key en en",
    "SVM": "es vi em",
    "HDBSCAN": "eyç di bi sken",
    "AUC": "ey yu si",
    "ROC": "ar o si",
    "MSE": "em es i",
    "RMSE": "ar em es i",
    "MAE": "em ey i",
    "WER": "dabıl yu i ar",
    "CER": "si i ar",
    "BLEU": "blü",
    "ROUGE": "ruj",
    "METEOR": "meteor",
    "MMLU": "em em el yu",
    "MMLU-Pro": "em em el yu pro",
    "HellaSwag": "hela sveg",
    "GSM8K": "ci es em eyt key",
    "HumanEval": "hyuman eval",
    "MBPP": "em bi pi pi",
    "MTEB": "em ti i bi",
    "GLUE": "glu",
    "SQuAD": "skuad",
    "CoT": "si o ti",
    "ToT": "ti o ti",
    "LMM": "el em em",
    "VLM": "vi el em",
    "SLM": "es el em",
    "MLLM": "em el el em",
}

TECHNOLOGICAL_TERMS = {
    "API": "ey pi ay",
    "SDK": "es di key",
    "CLI": "si el ay",
    "GUI": "gu i",
    "UI": "yu ay",
    "UX": "yu eks",
    "IDE": "ay di i",
    "VSCode": "vi es kod",
    "Git": "git",
    "GitHub": "git hab",
    "Docker": "doker",
    "K8s": "key eyt es",
    "Kubernetes": "kubernetis",
    "DevOps": "dev ops",
    "SRE": "es ar i",
    "CI": "si ay",
    "CD": "si di",
    "QA": "kyu ey",
    "QC": "kyu si",
    "URL": "yu ar el",
    "URI": "yu ar ay",
    "WWW": "dabıl yu dabıl yu dabıl yu",
    "HTTP": "eyç ti ti pi",
    "HTTPS": "eyç ti ti pi es",
    "DNS": "di en es",
    "IP": "ay pi",
    "TCP": "ti si pi",
    "UDP": "yu di pi",
    "VPN": "vi pi en",
    "CDN": "si di en",
    "SSL": "es es el",
    "TLS": "ti el es",
    "SSH": "es es eyç",
    "FTP": "ef ti pi",
    "SFTP": "es ef ti pi",
    "SMTP": "es em ti pi",
    "IMAP": "ay map",
    "POP3": "pop üç",
    "OAuth": "o ot",
    "SSO": "es es o",
    "JWT": "cey dabıl yu ti",
    "OTP": "o ti pi",
    "MFA": "em ef ey",
    "2FA": "tu ef ey",
    "QR": "kyu ar",
    "CPU": "si pi yu",
    "RAM": "ram",
    "ROM": "rom",
    "SSD": "es es di",
    "HDD": "eyç di di",
    "USB": "yu es bi",
    "HDMI": "eyç di em ay",
    "VM": "vi em",
    "VPS": "vi pi es",
    "DB": "di bi",
    "BI": "bi ay",
    "ETL": "i ti el",
    "ELT": "i el ti",
    "SQL": "es ku el",
    "NoSQL": "no es ku el",
    "GraphQL": "graf kyu el",
    "REST": "rest",
    "SOAP": "sop",
    "JSON": "cey son",
    "YAML": "yemıl",
    "XML": "eks em el",
    "HTML": "eyç ti em el",
    "CSS": "si es es",
    "JS": "cey es",
    "TS": "ti es",
    "TypeScript": "taypskript",
    "Node.js": "nod cey es",
    "NPM": "en pi em",
    "CSV": "si es vi",
    "PDF": "pi di ef",
    "PNG": "pi en ci",
    "JPG": "cey pi ci",
    "JPEG": "cey peg",
    "SVG": "es vi ci",
    "GIF": "gif",
    "MP4": "em pi dört",
    "MP3": "em pi üç",
    "WAV": "vev",
    "WebRTC": "veb ar ti si",
    "WebGL": "veb ci el",
    "WebGPU": "veb ci pi yu",
    "IoT": "ay o ti",
    "NFC": "en ef si",
    "RFID": "ar ef ay di",
    "AR": "ey ar",
    "VR": "vi ar",
    "MR": "em ar",
    "CMS": "si em es",
    "CRM": "si ar em",
    "ERP": "i ar pi",
    "HR": "eyç ar",
    "KPI": "key pi ay",
    "OKR": "o key ar",
    "SLA": "es el ey",
    "ROI": "ar o ay",
    "MVP": "em vi pi",
    "B2B": "bi tu bi",
    "B2C": "bi tu si",
    "D2C": "di tu si",
    "SaaS": "sas",
    "PaaS": "pas",
    "IaaS": "ayas",
    "POS": "pos",
    "WMS": "dabıl yu em es",
    "EDI": "i di ay",
    "FAQ": "ef ey kyu",
}

TECHNOLOGY_TERMS = {**AI_MODEL_TERMS, **TECHNOLOGICAL_TERMS}

# Lexical abbreviations (matched case-insensitively). Keys are lowercase.
ABBREVIATIONS = {
    "dr.": "doktor",
    "prof.": "profesör",
    "doç.": "doçent",
    "yrd.": "yardımcı",
    "av.": "avukat",
    "sn.": "sayın",
    "vs.": "vesaire",
    "vb.": "ve benzeri",
    "vd.": "ve diğerleri",
    "bkz.": "bakınız",
    "örn.": "örneğin",
    "yy.": "yüzyıl",
    "no.": "numara",
    "tel.": "telefon",
    "cad.": "cadde",
    "sok.": "sokak",
    "apt.": "apartman",
    "mah.": "mahalle",
}

# Units of measure (expanded only when they follow a number).
# Longer keys must appear before shorter prefix-matches (e.g. "°C" before "°").
UNITS = {
    "°C": "derece",
    "°F": "fahrenheit",
    "km²": "kilometre kare",
    "m²": "metre kare",
    "m³": "metre küp",
    "km/h": "kilometre bölü saat",
    "km/sa": "kilometre bölü saat",
    "m/s": "metre bölü saniye",
    "kWh": "kilowatt saat",
    "GHz": "gigahertz",
    "MHz": "megahertz",
    "kHz": "kilohertz",
    "Hz": "hertz",
    "kW": "kilowatt",
    "MW": "megawatt",
    "km": "kilometre",
    "cm": "santimetre",
    "mm": "milimetre",
    "kg": "kilogram",
    "mg": "miligram",
    "gr": "gram",
    "ml": "mililitre",
    "lt": "litre",
    "kb": "kilobayt",
    "mb": "megabayt",
    "gb": "gigabayt",
    "tb": "terabayt",
    "sa": "saat",
    "dk": "dakika",
    "sn": "saniye",
    "m": "metre",
    "g": "gram",
    "l": "litre",
}

# Currency symbols and codes -> spoken form.
CURRENCY = {
    "₺": "lira",
    "tl": "lira",
    "try": "lira",
    "$": "dolar",
    "usd": "dolar",
    "€": "avro",
    "eur": "avro",
    "£": "sterlin",
    "gbp": "sterlin",
    "₽": "ruble",
}

# Single-character symbols -> spoken form.
SYMBOLS = {
    "&": "ve",
    "@": "et",
    "°": "derece",
    "×": "çarpı",
    "÷": "bölü",
    "+": "artı",
    "=": "eşittir",
    "₊": "artı",
    "≠": "eşit değil",
    "≤": "küçük eşit",
    "≥": "büyük eşit",
    "√": "karekök",
    "∞": "sonsuz",
    "π": "pi",
}
